### PR TITLE
remove vendored cloudpickle

### LINKED ISSUE #62: Stop vendoring cloudpickle
Just a thought - since there are now regular fixes for new Python versions upstream (see https://github.com/cloudpipe/cloudpickle/commits/master) maybe we should stop trying to vendor our own version and always be out of date. The rate of Python internal changes does seem to be increasing...
Both [conda-forge](https://github.com/conda-forge/cloudpickle-feedstock) and [Ubuntu](https://packages.ubuntu.com/kinetic/python3-cloudpickle) provide packages for `cloudpickle`. Of course you can also `pip install` it so not really hard for a user to obtain. 
How about we remove it from `rios` and expect the user to have it installed if they are using the `parallel` functionality (users who aren't will see no difference)?

I can modify the conda-forge recipe to install it when `rios` is installed.

### PR DESCRIPTION
**Pull request by gillins**
Fixes #62

### CODE REVIEW

**Comment by neilflood** [comment]
Seems fine to me, thank you.

**Comment by gillins** [comment]
Hmm, seems there is a difference with the non-vendored one...
```
  File "/usr/local/lib/python3.10/dist-packages/rios/parallel/aws/batch.py", line 181, in startOneJob
    allInputsPickled = cloudpickle.dumps(allInputs)
AttributeError: module 'cloudpickle.cloudpickle' has no attribute 'dumps'
```

**Comment by neilflood** [comment]
That's weird. It seems it is supposed to be there, as per the current docs
https://pypi.org/project/cloudpickle/
Looks like the import is a bit different?

**Comment by gillins** [comment]
Yep should be just `import cloudpickle`, weird we might have had this wrong for people with it installed since forever...

**Pull request merged**
