### PR TITLE
report usage for compute workers

### PR DESCRIPTION
**Pull request by gillins**
@neilflood any thoughts on this? Is there a better way of doing this?

The problem is that for Batch (and SLURM etc no doubt) you have to say ahead of time how much memory you are going to be using. There is no real way to do this apart from running with heaps of mem on a subset and seeing how much you use (with this PR). Then refine the amount you ask for and go from there.

### CODE REVIEW

**Comment by neilflood** [comment]
Hmmmm.... something to consider, I can see. 

I am not too keen on just a print statement. However, I do see the need for being able to report details of the compute worker jobs, in order to adjust things. 

I am surprised that memory is a significant issue, though. Each worker should only ever be processing a single block at a time, and unless you use a really large block size, I would have expected this never to come up. Is that not true?

I would quite like to have a careful think about this, and see if there is not  better way. I am leaning more towards something which reports more information back to the main script, perhaps via the compute manager object. That way each different compute worker kind could report, but they would end up much the same back in the main script.

**Comment by gillins** [comment]
Yes this is a large block and heavy compute situation. Yes I was wondering about reporting back, but wondered if that was overkill.

**Comment by neilflood** [comment]
re: large blocks. Ah, OK, that makes sense, then. 

re: reporting back. I think that if it has come up for one situation already, then it is going to arise in other ways, so we should think about a neat and general mechanism. You are wanting memory size now, but soon you will also want the time spent (PBS and SLURM also require those to be specified), and one could imagine other details of a run may become relevant. I think a general reporting mechanism will be worth it in the long run, despite the initial pain involved. 

Thank you for finding the resource module, though - I was unaware that existed. Good to know about. :-)

**Comment by neilflood** [comment]
Just looking at what I already have in ComputeWorkerManager. There is a generic field `outObjList`, which is a list of all objects intended to go back to the main routine. Currently this is used for the otherArgs stuff, and for error reporting, but I made it fairly general, so I think this could also be used to report usage information for each worker. Such information could then be added to the ApplierReturn object, and thus be fully available to the main script.

**Comment by gillins** [comment]
I've just remembered that the `resource` module is Unix specific. So we'll have to add a guard here that it can in fact be imported and cope when it isn't available.
Regarding time spent, I'm guessing this is less of a problem as this should be about the same as the time the main script takes to run. And will change with the size of input image(s).

**Comment by neilflood** [comment]
After discussion and experimentation offline, we decided that most of this kind of need can be met using the [psutil](https://psutil.readthedocs.io/) package from within the user function, and passing data back via the otherArgs object. So, we are not going to action this any further.

**Pull request closed without merging**
