### PR TITLE
Cope with numpy-1.24 type symbol deprecations

### PR DESCRIPTION
**Pull request by neilflood**
This now passes standard tests under numpy-1.24.0.

### CODE REVIEW

**Comment by neilflood** [comment]
Dammit, a typo in the commit message - I hate that......

**Comment by gillins** [comment]
Should we also be coping with int64/uint64 (not sure why we didn't do this earlier). And the int8 support coming to GDAL soon (https://gdal.org/development/rfc/rfc87_signed_int8.html)....

**Comment by gillins** [comment]
> Dammit, a typo in the commit message - I hate that......

You can edit the title of this PR at least. When you do a squash and merge the originally commit message will be lost anyway.

**Comment by neilflood** [comment]
I think we do already cope with int64/uint64. There is a little extra couple of lines to add to that list, if gdalconst has GDT_Int64. 

Thanks, edited the title, at least :-)

**Comment by neilflood** [comment]
By the way, I also tested these changes under numpy-1.23, and it works fine there, too.

**Review by gillins — APPROVED** [review]

**Pull request merged**
