### PR TITLE
remove old caching code

### PR DESCRIPTION
**Pull request by gillins**
This stuff came across from PyModeller. Has anyone ever used it?

Now that we have the wonderful `fileinfo` and the standalone `rat` module this all seems a but unnecessary.

What do you think?

### CODE REVIEW

**Comment by neilflood** [comment]
Wow, cleaning up historical dead wood. Excellent, I love it!

Yes, I agree with removing this. It was only in the PyModeller code in mimicry of Imagine modeller, and I agree that `fileinfo` and `rat` are better ways of doing this kind of thing. I am not sure if anyone ever used it.

I wonder how best to communicate to any possible users what to do if their code does fail? I guess we could wait until someone raises an issue about failures in a subsequent release, and explain it then? My bet is no-one will ever complain. 

A really "responsible" project would add deprecation messages, wait three releases, and then remove it. But we are cowboys..... :-)

**Comment by gillins** [comment]
Cowboys! Perfect - that's it - we have the theme for the next launch party! Well done.

**Comment by gillins** [comment]
I don't think anyone ever used it and I'm pretty sure no one will complain. We don't mention it in the Applier Examples or anywhere else AFAICT.

**Comment by neilflood** [comment]
I agree.

While you are in the headspace, could you make a list of all the methods which are being removed, so we can include it in the release notes when we next do a release? Maybe just add it into a comment here, just to save us having to go through and do that later?

Then feel free to merge when you are happy.

**Comment by gillins** [comment]
```
ApplierControls.statsCache
ApplierControls.setStatsCache()
ReaderInfo.getAttributeColumn()
ReaderInfo.global_stats()
ReaderInfo.global_min()
ReaderInfo.global_max()
ReaderInfo.global_mean()
ReaderInfo.global_stddev()
```

**Pull request merged**
