### PR TITLE
use setuptools rather than numpy.distutils for install

### PR DESCRIPTION
**Pull request by gillins**
`numpy.distutils` is now deprecated. See https://numpy.org/devdocs/reference/distutils_status_migration.html#distutils-status-migration

### CODE REVIEW

**Comment by gillins** [comment]
Seems to create a `.egg` directory with adds to path by appending to `easy-install.pth`. Messy, but I guess everyone is doing this now...

**Comment by gillins** [comment]
```
Starting test: TESTSTATS
TESTSTATS: Datatype=KEA Int64 scale=30000
Error in median: 750000.0 (from file) != 1860000.0 (from array)
Error in mode: 750000.0 (from file) != 1500000.0 (from array)
TESTSTATS: Note that the mode and median tests will fail in GDAL < 2.0, unless the GDAL fixes suggested in tickets http://trac.osgeo.org/gdal/ticket/4750 and http://trac.osgeo.org/gdal/ticket/5289 are applied
```
Any ideas? conda is now providing `gdal` 3.5.1 which has the 64 bit KEA fixes....

**Comment by neilflood** [comment]
This is great, it makes me very glad I added the 64-bit tests. 

Just looking now, it seems that the value from the array is correct, and thus the value from the file is not. This is the value done within calcstats.py, so that suggests the code there needs some sort of tweak for 64-bit. It is not obvious to me just yet, but I think that is where we need to look.

**Comment by gillins** [comment]
@neilflood are you happy for this to be merged while we wait for gdal 3.5.2?

**Comment by neilflood** [comment]
Yes, merge away!

**Pull request merged**
